In [61]:
# Initial imports
import os
import pandas as pd
import numpy as np
import hvplot.pandas
from pathlib import Path
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi
import warnings
warnings.filterwarnings("ignore")

In [62]:
env_path = Path("../.env")
load_dotenv(dotenv_path=env_path)

Python-dotenv could not parse statement starting at line 1

True

In [63]:
API_KEY = os.getenv("ALPACA_API_KEY")
API_SECRET = os.getenv("ALPACA_SECRET_KEY")
ALPACA_API_BASE_URL = "https://paper-api.alpaca.markets"

In [64]:
alpaca = tradeapi.REST(
    API_KEY,
    API_SECRET,
    ALPACA_API_BASE_URL,
    api_version="v2")

In [65]:
eth_ticker = ["ETHUSD"]
btc_ticker = ["BTCUSD"]

In [66]:
start_date = pd.Timestamp("2021-01-01", tz="America/New_York").isoformat()
end_date = pd.Timestamp("2022-01-01", tz="America/New_York").isoformat()

In [67]:
timeframe = "1Day"

In [68]:
eth_data_df = alpaca.get_crypto_bars(
    eth_ticker,
    timeframe,
    start = start_date,
    end = end_date
).df

display(eth_data_df.head())

,exchange,open,high,low,close,volume,trade_count,vwap,symbol
timestamp,,,,,,,,,
2021-01-01 06:00:00+00:00,CBSE,730.97,739.00,715.22,734.62,46104.154992,26556,728.392387,ETHUSD
2021-01-01 06:00:00+00:00,FTXU,739.08,745.04,717.28,731.78,116.743000,97,724.373273,ETHUSD
2021-01-02 06:00:00+00:00,CBSE,775.29,791.22,770.00,787.32,71896.942065,47622,780.118416,ETHUSD
2021-01-02 06:00:00+00:00,FTXU,736.30,787.93,723.24,785.00,1813.553000,210,774.227444,ETHUSD
2021-01-03 06:00:00+00:00,CBSE,980.44,1098.47,955.00,1088.78,213416.375742,114506,1010.719458,ETHUSD

In [69]:
eth_data_df["actual returns"] = eth_data_df["close"].pct_change()

eth_data_df = eth_data_df.dropna()

In [70]:
eth_prices_df = eth_data_df[['symbol', 'open', 'high', 'low', 'close', 'volume', 'actual returns']]
display(eth_prices_df.head())
display(eth_prices_df.tail())

,symbol,open,high,low,close,volume,actual returns
timestamp,,,,,,,
2021-01-01 06:00:00+00:00,ETHUSD,739.08,745.04,717.28,731.78,116.743000,-0.003866
2021-01-02 06:00:00+00:00,ETHUSD,775.29,791.22,770.00,787.32,71896.942065,0.075897
2021-01-02 06:00:00+00:00,ETHUSD,736.30,787.93,723.24,785.00,1813.553000,-0.002947
2021-01-03 06:00:00+00:00,ETHUSD,980.44,1098.47,955.00,1088.78,213416.375742,0.386981
2021-01-03 06:00:00+00:00,ETHUSD,787.43,1097.02,787.43,1094.88,9454.058000,0.005603

,symbol,open,high,low,close,volume,actual returns
timestamp,,,,,,,
2021-12-30 06:00:00+00:00,ETHUSD,3680.81,3768.79,3680.81,3750.00,1394.116200,0.002478
2021-12-30 06:00:00+00:00,ETHUSD,3674.90,3768.00,3670.40,3741.30,5493.301000,-0.002320
2021-12-31 06:00:00+00:00,ETHUSD,3740.53,3813.23,3619.78,3735.04,126966.898964,-0.001673
2021-12-31 06:00:00+00:00,ETHUSD,3711.22,3809.85,3620.86,3738.96,868.922000,0.001050
2021-12-31 06:00:00+00:00,ETHUSD,3740.00,3813.20,3622.40,3729.10,13955.507000,-0.002637

In [71]:
eth_prices_df.index = eth_prices_df.index.date
eth_prices_df

,symbol,open,high,low,close,volume,actual returns
2021-01-01,ETHUSD,739.08,745.04,717.28,731.78,116.743000,-0.003866
2021-01-02,ETHUSD,775.29,791.22,770.00,787.32,71896.942065,0.075897
2021-01-02,ETHUSD,736.30,787.93,723.24,785.00,1813.553000,-0.002947
2021-01-03,ETHUSD,980.44,1098.47,955.00,1088.78,213416.375742,0.386981
2021-01-03,ETHUSD,787.43,1097.02,787.43,1094.88,9454.058000,0.005603
...,...,...,...,...,...,...,...
2021-12-30,ETHUSD,3680.81,3768.79,3680.81,3750.00,1394.116200,0.002478
2021-12-30,ETHUSD,3674.90,3768.00,3670.40,3741.30,5493.301000,-0.002320
2021-12-31,ETHUSD,3740.53,3813.23,3619.78,3735.04,126966.898964,-0.001673
2021-12-31,ETHUSD,3711.22,3809.85,3620.86,3738.96,868.922000,0.001050
2021-12-31,ETHUSD,3740.00,3813.20,3622.40,3729.10,13955.507000,-0.002637

In [72]:
btc_data_df = alpaca.get_crypto_bars(
    btc_ticker,
    timeframe,
    start = start_date,
    end = end_date
).df

display(btc_data_df.head())

,exchange,open,high,low,close,volume,trade_count,vwap,symbol
timestamp,,,,,,,,,
2021-01-01 06:00:00+00:00,CBSE,29413.29,29683.50,29039.00,29683.03,4431.837894,44893,29419.838845,BTCUSD
2021-01-01 06:00:00+00:00,FTXU,29225.00,29631.00,28750.00,29631.00,25.076500,211,29330.826766,BTCUSD
2021-01-02 06:00:00+00:00,CBSE,32222.88,34205.00,32008.62,33779.48,7955.017558,87151,33089.671665,BTCUSD
2021-01-02 06:00:00+00:00,FTXU,29585.00,34172.50,29566.50,33666.50,237.162400,1742,32113.173543,BTCUSD
2021-01-03 06:00:00+00:00,CBSE,33082.83,33666.99,32453.37,32903.87,7401.195215,77379,33140.775678,BTCUSD

In [73]:
btc_data_df["actual returns"] = btc_data_df["close"].pct_change()

btc_data_df = btc_data_df.dropna()

In [74]:
btc_prices_df = btc_data_df[['symbol', 'open', 'high', 'low', 'close', 'volume', "actual returns"]]

display(btc_prices_df.head())
display(btc_prices_df.tail())

,symbol,open,high,low,close,volume,actual returns
timestamp,,,,,,,
2021-01-01 06:00:00+00:00,BTCUSD,29225.00,29631.00,28750.00,29631.00,25.076500,-0.001753
2021-01-02 06:00:00+00:00,BTCUSD,32222.88,34205.00,32008.62,33779.48,7955.017558,0.140005
2021-01-02 06:00:00+00:00,BTCUSD,29585.00,34172.50,29566.50,33666.50,237.162400,-0.003345
2021-01-03 06:00:00+00:00,BTCUSD,33082.83,33666.99,32453.37,32903.87,7401.195215,-0.022652
2021-01-03 06:00:00+00:00,BTCUSD,33791.50,34820.50,32335.00,32919.00,291.519200,0.000460

,symbol,open,high,low,close,volume,actual returns
timestamp,,,,,,,
2021-12-30 06:00:00+00:00,BTCUSD,46918.00,47900.8,46752.4,47179.20,184.718400,-0.002253
2021-12-30 06:00:00+00:00,BTCUSD,46761.00,47906.0,46720.0,47315.00,695.833600,0.002878
2021-12-31 06:00:00+00:00,BTCUSD,47285.73,48574.7,45650.0,47187.99,12887.901811,-0.002684
2021-12-31 06:00:00+00:00,BTCUSD,47104.70,48578.9,45778.0,47284.40,96.188100,0.002043
2021-12-31 06:00:00+00:00,BTCUSD,47277.00,48569.0,45663.0,47185.00,1659.854800,-0.002102

In [75]:
btc_prices_df.index = btc_prices_df.index.date
btc_prices_df

,symbol,open,high,low,close,volume,actual returns
2021-01-01,BTCUSD,29225.00,29631.00,28750.00,29631.00,25.076500,-0.001753
2021-01-02,BTCUSD,32222.88,34205.00,32008.62,33779.48,7955.017558,0.140005
2021-01-02,BTCUSD,29585.00,34172.50,29566.50,33666.50,237.162400,-0.003345
2021-01-03,BTCUSD,33082.83,33666.99,32453.37,32903.87,7401.195215,-0.022652
2021-01-03,BTCUSD,33791.50,34820.50,32335.00,32919.00,291.519200,0.000460
...,...,...,...,...,...,...,...
2021-12-30,BTCUSD,46918.00,47900.80,46752.40,47179.20,184.718400,-0.002253
2021-12-30,BTCUSD,46761.00,47906.00,46720.00,47315.00,695.833600,0.002878
2021-12-31,BTCUSD,47285.73,48574.70,45650.00,47187.99,12887.901811,-0.002684
2021-12-31,BTCUSD,47104.70,48578.90,45778.00,47284.40,96.188100,0.002043
2021-12-31,BTCUSD,47277.00,48569.00,45663.00,47185.00,1659.854800,-0.002102

In [76]:
display(eth_prices_df.head(10))
display(eth_prices_df.tail(10))

,symbol,open,high,low,close,volume,actual returns
2021-01-01,ETHUSD,739.08,745.04,717.28,731.78,116.743000,-0.003866
2021-01-02,ETHUSD,775.29,791.22,770.00,787.32,71896.942065,0.075897
2021-01-02,ETHUSD,736.30,787.93,723.24,785.00,1813.553000,-0.002947
2021-01-03,ETHUSD,980.44,1098.47,955.00,1088.78,213416.375742,0.386981
2021-01-03,ETHUSD,787.43,1097.02,787.43,1094.88,9454.058000,0.005603
2021-01-04,ETHUSD,1087.55,1168.99,886.33,1042.38,765246.607376,-0.047950
2021-01-04,ETHUSD,1093.38,1152.16,888.88,992.06,1078.603000,-0.048274
2021-01-05,ETHUSD,990.22,1125.81,980.00,1103.73,444497.096675,0.112564
2021-01-05,ETHUSD,1002.08,1137.36,1002.08,1094.49,2435.340000,-0.008372
2021-01-06,ETHUSD,1106.30,1215.79,1092.70,1212.02,530453.913203,0.107383

,symbol,open,high,low,close,volume,actual returns
2021-12-28,ETHUSD,3922.10,3936.60,3760.70,3802.80,17894.745000,0.001907
2021-12-29,ETHUSD,3802.78,3825.24,3588.02,3674.02,112489.242063,-0.033865
2021-12-29,ETHUSD,3794.22,3819.52,3584.99,3668.62,2724.032200,-0.001470
2021-12-29,ETHUSD,3804.60,3822.50,3581.50,3671.10,23102.671000,0.000676
2021-12-30,ETHUSD,3675.26,3769.99,3667.49,3740.73,89525.331250,0.018967
2021-12-30,ETHUSD,3680.81,3768.79,3680.81,3750.00,1394.116200,0.002478
2021-12-30,ETHUSD,3674.90,3768.00,3670.40,3741.30,5493.301000,-0.002320
2021-12-31,ETHUSD,3740.53,3813.23,3619.78,3735.04,126966.898964,-0.001673
2021-12-31,ETHUSD,3711.22,3809.85,3620.86,3738.96,868.922000,0.001050
2021-12-31,ETHUSD,3740.00,3813.20,3622.40,3729.10,13955.507000,-0.002637

In [77]:
display(btc_prices_df.head(10))
display(btc_prices_df.tail(10))

,symbol,open,high,low,close,volume,actual returns
2021-01-01,BTCUSD,29225.00,29631.00,28750.00,29631.00,25.076500,-0.001753
2021-01-02,BTCUSD,32222.88,34205.00,32008.62,33779.48,7955.017558,0.140005
2021-01-02,BTCUSD,29585.00,34172.50,29566.50,33666.50,237.162400,-0.003345
2021-01-03,BTCUSD,33082.83,33666.99,32453.37,32903.87,7401.195215,-0.022652
2021-01-03,BTCUSD,33791.50,34820.50,32335.00,32919.00,291.519200,0.000460
2021-01-04,BTCUSD,32020.22,32890.00,30020.00,30460.19,11908.475812,-0.074693
2021-01-04,BTCUSD,33013.00,33448.50,27794.00,30464.50,642.743000,0.000141
2021-01-05,BTCUSD,34043.91,35848.99,33352.54,35130.05,11648.279116,0.153147
2021-01-05,BTCUSD,30493.00,35878.50,29900.00,34863.00,999.822400,-0.007602
2021-01-06,BTCUSD,36859.26,37823.00,36511.51,37505.58,10013.729631,0.075799

,symbol,open,high,low,close,volume,actual returns
2021-12-28,BTCUSD,49201.00,49454.00,47320.00,47901.00,1417.842500,-0.001459
2021-12-29,BTCUSD,47904.86,48080.64,45981.65,46778.41,14704.177180,-0.023436
2021-12-29,BTCUSD,47775.60,48069.70,45999.00,46762.00,329.183800,-0.000351
2021-12-29,BTCUSD,47899.00,48091.00,45947.00,46749.00,1521.402400,-0.000278
2021-12-30,BTCUSD,46766.07,47926.15,46709.34,47285.73,16544.913259,0.011481
2021-12-30,BTCUSD,46918.00,47900.80,46752.40,47179.20,184.718400,-0.002253
2021-12-30,BTCUSD,46761.00,47906.00,46720.00,47315.00,695.833600,0.002878
2021-12-31,BTCUSD,47285.73,48574.70,45650.00,47187.99,12887.901811,-0.002684
2021-12-31,BTCUSD,47104.70,48578.90,45778.00,47284.40,96.188100,0.002043
2021-12-31,BTCUSD,47277.00,48569.00,45663.00,47185.00,1659.854800,-0.002102

In [78]:
eth_prices_df = eth_prices_df.loc[~eth_prices_df.index.duplicated(), :]
btc_prices_df = btc_prices_df.loc[~btc_prices_df.index.duplicated(), :]

In [79]:
display(eth_prices_df.head(10))
display(eth_prices_df.tail(10))

,symbol,open,high,low,close,volume,actual returns
2021-01-01,ETHUSD,739.08,745.04,717.28,731.78,116.743000,-0.003866
2021-01-02,ETHUSD,775.29,791.22,770.00,787.32,71896.942065,0.075897
2021-01-03,ETHUSD,980.44,1098.47,955.00,1088.78,213416.375742,0.386981
2021-01-04,ETHUSD,1087.55,1168.99,886.33,1042.38,765246.607376,-0.047950
2021-01-05,ETHUSD,990.22,1125.81,980.00,1103.73,444497.096675,0.112564
2021-01-06,ETHUSD,1106.30,1215.79,1092.70,1212.02,530453.913203,0.107383
2021-01-07,ETHUSD,1227.55,1233.93,1063.18,1148.89,222130.104221,-0.058943
2021-01-08,ETHUSD,1148.83,1275.00,1124.27,1217.35,466618.499280,0.069070
2021-01-09,ETHUSD,1281.25,1345.46,1281.25,1319.09,139378.949497,0.114096
2021-01-10,ETHUSD,1255.10,1260.24,1003.68,1091.91,330525.037750,-0.174066

,symbol,open,high,low,close,volume,actual returns
2021-12-22,ETHUSD,4036.11,4064.28,3912.12,3947.06,89922.985110,-0.021867
2021-12-23,ETHUSD,3947.00,4153.43,3895.70,4091.67,132572.799713,0.036338
2021-12-24,ETHUSD,4091.16,4138.35,4023.50,4048.75,80892.426606,-0.010207
2021-12-25,ETHUSD,4048.75,4143.13,4008.01,4030.48,62609.148670,-0.004623
2021-12-26,ETHUSD,4030.58,4106.50,4021.20,4064.75,59222.112627,0.008298
2021-12-27,ETHUSD,4064.76,4128.31,3882.69,3922.41,106557.220246,-0.034389
2021-12-28,ETHUSD,3922.41,3935.04,3760.37,3802.79,118648.892044,-0.030667
2021-12-29,ETHUSD,3802.78,3825.24,3588.02,3674.02,112489.242063,-0.033865
2021-12-30,ETHUSD,3675.26,3769.99,3667.49,3740.73,89525.331250,0.018967
2021-12-31,ETHUSD,3740.53,3813.23,3619.78,3735.04,126966.898964,-0.001673

In [80]:
display(btc_prices_df.head(10))
display(btc_prices_df.tail(10))

,symbol,open,high,low,close,volume,actual returns
2021-01-01,BTCUSD,29225.00,29631.00,28750.00,29631.00,25.076500,-0.001753
2021-01-02,BTCUSD,32222.88,34205.00,32008.62,33779.48,7955.017558,0.140005
2021-01-03,BTCUSD,33082.83,33666.99,32453.37,32903.87,7401.195215,-0.022652
2021-01-04,BTCUSD,32020.22,32890.00,30020.00,30460.19,11908.475812,-0.074693
2021-01-05,BTCUSD,34043.91,35848.99,33352.54,35130.05,11648.279116,0.153147
2021-01-06,BTCUSD,36859.26,37823.00,36511.51,37505.58,10013.729631,0.075799
2021-01-07,BTCUSD,39510.55,39750.00,36579.00,38000.87,10491.715584,0.011940
2021-01-08,BTCUSD,38001.76,41986.37,37572.01,40665.15,30972.072189,0.069812
2021-01-09,BTCUSD,40255.40,41452.12,40205.00,40571.12,5789.461315,0.032173
2021-01-10,BTCUSD,38168.89,38273.88,33333.34,34847.17,16737.697083,-0.140838

,symbol,open,high,low,close,volume,actual returns
2021-12-22,BTCUSD,48998.06,49555.00,48073.53,48396.21,8844.162203,-0.011939
2021-12-23,BTCUSD,48395.60,51527.62,48050.05,51029.00,13496.971784,0.054907
2021-12-24,BTCUSD,51029.00,51851.62,50492.52,50912.36,8305.707583,-0.001718
2021-12-25,BTCUSD,50912.37,51154.70,49650.00,49894.37,5019.621503,-0.021353
2021-12-26,BTCUSD,49896.02,51295.33,49592.91,50882.33,5462.835100,0.020340
2021-12-27,BTCUSD,50882.34,52025.00,48755.01,49221.76,12915.776618,-0.032876
2021-12-28,BTCUSD,49217.17,49467.89,47321.02,47909.37,14424.510771,-0.026747
2021-12-29,BTCUSD,47904.86,48080.64,45981.65,46778.41,14704.177180,-0.023436
2021-12-30,BTCUSD,46766.07,47926.15,46709.34,47285.73,16544.913259,0.011481
2021-12-31,BTCUSD,47285.73,48574.70,45650.00,47187.99,12887.901811,-0.002684

In [81]:
eth_trading_df = eth_prices_df.loc[:,['close', 'actual returns']]
btc_trading_df = btc_prices_df.loc[:,['close', 'actual returns']]

In [82]:
eth_trading_df.index.names = ['ETH']
btc_trading_df.index.names = ['BTC']

In [83]:
short_window = 5
long_window = 23

In [84]:
eth_trading_df["SMA5"] = eth_trading_df["close"].rolling(window=short_window).mean()
eth_trading_df["SMA23"] = eth_trading_df["close"].rolling(window=long_window).mean()

In [85]:
btc_trading_df["SMA5"] = btc_trading_df["close"].rolling(window=short_window).mean()
btc_trading_df["SMA23"] = btc_trading_df["close"].rolling(window=long_window).mean()

In [86]:
eth_trading_df = eth_trading_df.dropna()
btc_trading_df = btc_trading_df.dropna()

In [87]:
eth_trading_df['signal'] = 0.0
btc_trading_df['signal'] = 0.0

In [88]:
display(eth_trading_df.head(10))
display(btc_trading_df.head(10))

              close  actual returns      SMA5        SMA23  signal
ETH
2021-01-23  1326.08        0.066667  1268.852  1149.432609     0.0
2021-01-24  1441.87        0.087793  1283.618  1180.306087     0.0
2021-01-25  1317.97       -0.078858  1286.028  1203.377826     0.0
2021-01-26  1286.15       -0.041474  1321.134  1211.959130     0.0
2021-01-27  1240.96       -0.032012  1322.606  1220.593043     0.0
2021-01-28  1305.38        0.000905  1318.466  1229.360435     0.0
2021-01-29  1379.87        0.059076  1306.066  1236.658261     0.0
2021-01-30  1351.69        0.001252  1312.810  1245.475652     0.0
2021-01-31  1322.00       -0.018705  1319.980  1250.025652     0.0
2021-02-01  1389.48        0.049615  1349.684  1253.086087     0.0

               close  actual returns       SMA5         SMA23  signal
BTC
2021-01-23  32865.87       -0.013126  33354.942  35196.071739     0.0
2021-01-24  33356.55        0.016937  32925.284  35358.052174     0.0
2021-01-25  32090.10       -0.035348  32430.680  35284.600870     0.0
2021-01-26  31551.72       -0.022773  32569.834  35225.811739     0.0
2021-01-27  30407.13       -0.035490  32054.274  35223.504783     0.0
2021-01-28  33052.81        0.045247  32091.662  35133.190000     0.0
2021-01-29  34262.11        0.037743  32272.774  34992.169565     0.0
2021-01-30  34315.63        0.025357  32717.880  34831.941739     0.0
2021-01-31  33800.00        0.001511  33167.536  34533.456957     0.0
2021-02-01  34022.03        0.007195  33890.516  34248.713913     0.0

In [89]:
eth_X = eth_trading_df[['SMA5', 'SMA23']].shift().dropna().copy()


display(eth_X.head())
display(eth_X.tail())

                SMA5        SMA23
ETH
2021-01-24  1268.852  1149.432609
2021-01-25  1283.618  1180.306087
2021-01-26  1286.028  1203.377826
2021-01-27  1321.134  1211.959130
2021-01-28  1322.606  1220.593043

                SMA5        SMA23
ETH
2021-12-27  4036.542  4050.903913
2021-12-28  4031.612  4038.440435
2021-12-29  3973.836  4023.777391
2021-12-30  3898.890  3994.386087
2021-12-31  3840.940  3968.804348

In [90]:
btc_X = btc_trading_df[['SMA5', 'SMA23']].shift().dropna().copy()


display(btc_X.head())
display(btc_X.tail())

                 SMA5         SMA23
BTC
2021-01-24  33354.942  35196.071739
2021-01-25  32925.284  35358.052174
2021-01-26  32430.680  35284.600870
2021-01-27  32569.834  35225.811739
2021-01-28  32054.274  35223.504783

                 SMA5         SMA23
BTC
2021-12-27  50222.854  48943.026522
2021-12-28  50387.964  48930.071304
2021-12-29  49764.038  48893.147391
2021-12-30  48937.248  48712.031304
2021-12-31  48415.520  48574.035217

In [91]:
display(btc_trading_df.head())
display(btc_trading_df.tail())

               close  actual returns       SMA5         SMA23  signal
BTC
2021-01-23  32865.87       -0.013126  33354.942  35196.071739     0.0
2021-01-24  33356.55        0.016937  32925.284  35358.052174     0.0
2021-01-25  32090.10       -0.035348  32430.680  35284.600870     0.0
2021-01-26  31551.72       -0.022773  32569.834  35225.811739     0.0
2021-01-27  30407.13       -0.035490  32054.274  35223.504783     0.0

               close  actual returns       SMA5         SMA23  signal
BTC
2021-12-27  49221.76       -0.032876  50387.964  48930.071304     0.0
2021-12-28  47909.37       -0.026747  49764.038  48893.147391     0.0
2021-12-29  46778.41       -0.023436  48937.248  48712.031304     0.0
2021-12-30  47285.73        0.011481  48415.520  48574.035217     0.0
2021-12-31  47187.99       -0.002684  47676.652  48425.335652     0.0

In [92]:
eth_trading_df.loc[(eth_trading_df['SMA5'] > eth_trading_df['SMA23']), 'signal'] = 1


eth_trading_df.loc[(eth_trading_df['SMA5'] < eth_trading_df['SMA23']), 'signal'] = -1

In [93]:
btc_trading_df.loc[(btc_trading_df['SMA5'] > btc_trading_df['SMA23']), 'signal'] = 1


btc_trading_df.loc[(btc_trading_df['SMA5'] < btc_trading_df['SMA23']), 'signal'] = -1

In [94]:
display(btc_trading_df.head())
display(btc_trading_df.tail())

               close  actual returns       SMA5         SMA23  signal
BTC
2021-01-23  32865.87       -0.013126  33354.942  35196.071739    -1.0
2021-01-24  33356.55        0.016937  32925.284  35358.052174    -1.0
2021-01-25  32090.10       -0.035348  32430.680  35284.600870    -1.0
2021-01-26  31551.72       -0.022773  32569.834  35225.811739    -1.0
2021-01-27  30407.13       -0.035490  32054.274  35223.504783    -1.0

               close  actual returns       SMA5         SMA23  signal
BTC
2021-12-27  49221.76       -0.032876  50387.964  48930.071304     1.0
2021-12-28  47909.37       -0.026747  49764.038  48893.147391     1.0
2021-12-29  46778.41       -0.023436  48937.248  48712.031304     1.0
2021-12-30  47285.73        0.011481  48415.520  48574.035217    -1.0
2021-12-31  47187.99       -0.002684  47676.652  48425.335652    -1.0

In [95]:
eth_y = eth_trading_df['signal'].copy()
btc_y = btc_trading_df['signal'].copy()

In [96]:
display(btc_trading_df.head())
display(btc_trading_df.tail())

               close  actual returns       SMA5         SMA23  signal
BTC
2021-01-23  32865.87       -0.013126  33354.942  35196.071739    -1.0
2021-01-24  33356.55        0.016937  32925.284  35358.052174    -1.0
2021-01-25  32090.10       -0.035348  32430.680  35284.600870    -1.0
2021-01-26  31551.72       -0.022773  32569.834  35225.811739    -1.0
2021-01-27  30407.13       -0.035490  32054.274  35223.504783    -1.0

               close  actual returns       SMA5         SMA23  signal
BTC
2021-12-27  49221.76       -0.032876  50387.964  48930.071304     1.0
2021-12-28  47909.37       -0.026747  49764.038  48893.147391     1.0
2021-12-29  46778.41       -0.023436  48937.248  48712.031304     1.0
2021-12-30  47285.73        0.011481  48415.520  48574.035217    -1.0
2021-12-31  47187.99       -0.002684  47676.652  48425.335652    -1.0

In [97]:
from pandas.tseries.offsets import DateOffset

In [98]:
eth_training_begin = eth_X.index.min()
btc_training_begin = btc_X.index.min()


print(eth_training_begin)
print(btc_training_begin)

2021-01-24
2021-01-24

In [100]:
eth_training_end = eth_X.index.min() + DateOffset(months=5)
btc_training_end = btc_X.index.min() + DateOffset(months=6)


print(eth_training_end)
print(btc_training_end)

2021-06-24 00:00:00
2021-07-24 00:00:00

In [101]:
eth_X_train = eth_X.loc[eth_training_begin:eth_training_end]
eth_y_train = eth_y.loc[eth_training_begin:eth_training_end]

btc_X_train = btc_X.loc[btc_training_begin:btc_training_end]
btc_y_train = btc_y.loc[btc_training_begin:btc_training_end]

# Display sample data
display(eth_X_train.head())
display(btc_X_train.head())

                SMA5        SMA23
ETH
2021-01-24  1268.852  1149.432609
2021-01-25  1283.618  1180.306087
2021-01-26  1286.028  1203.377826
2021-01-27  1321.134  1211.959130
2021-01-28  1322.606  1220.593043

                 SMA5         SMA23
BTC
2021-01-24  33354.942  35196.071739
2021-01-25  32925.284  35358.052174
2021-01-26  32430.680  35284.600870
2021-01-27  32569.834  35225.811739
2021-01-28  32054.274  35223.504783

In [102]:
eth_X_test = eth_X.loc[eth_training_end:]
eth_y_test = eth_y.loc[eth_training_end:]

btc_X_test = btc_X.loc[btc_training_end:]
btc_y_test = btc_y.loc[btc_training_end:]


# Display sample data
eth_X_test

                SMA5        SMA23
ETH
2021-06-24  2029.338  2422.324348
2021-06-25  1983.324  2393.749130
2021-06-26  1925.728  2353.273043
2021-06-27  1898.112  2314.397391
2021-06-28  1916.430  2283.204348
...              ...          ...
2021-12-27  4036.542  4050.903913
2021-12-28  4031.612  4038.440435
2021-12-29  3973.836  4023.777391
2021-12-30  3898.890  3994.386087
2021-12-31  3840.940  3968.804348

[191 rows x 2 columns]

In [103]:
from sklearn.preprocessing import StandardScaler
from sklearn import svm

# Create a StandardScaler instance
scaler = StandardScaler()

In [104]:
eth_X_scaler = scaler.fit(eth_X_train)
btc_X_scaler = scaler.fit(btc_X_train)

# Transform the ETH & BTC  X_train and X_test DataFrames using the X_scaler
eth_X_train_scaled = eth_X_scaler.transform(eth_X_train)
eth_X_test_scaled = eth_X_scaler.transform(eth_X_test)

btc_X_train_scaled = btc_X_scaler.transform(btc_X_train)
btc_X_test_scaled = btc_X_scaler.transform(btc_X_test)

In [105]:
eth_svm_model = svm.SVC()
btc_svm_model = svm.SVC()

# Fit the model to the data using X_train_scaled and y_train
eth_svm_model = eth_svm_model.fit(eth_X_train_scaled, eth_y_train)
btc_svm_model = btc_svm_model.fit(btc_X_train_scaled, btc_y_train)

# Use the trained model to predict the trading signals for the training data
eth_training_signal_predictions = eth_svm_model.predict(eth_X_train_scaled)
btc_training_signal_predictions = btc_svm_model.predict(btc_X_train_scaled)

# Display the sample predictions
display(eth_training_signal_predictions[:10])
display(btc_training_signal_predictions[:10])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [108]:
from sklearn.metrics import classification_report

# Evaluate the model using a classification report
eth_training_report = classification_report(eth_y_train, eth_training_signal_predictions)
print(eth_training_report)

btc_training_report = classification_report(btc_y_train, btc_training_signal_predictions)
print(btc_training_report)

              precision    recall  f1-score   support

        -1.0       1.00      0.40      0.58        52
         1.0       0.76      1.00      0.87       100

    accuracy                           0.80       152
   macro avg       0.88      0.70      0.72       152
weighted avg       0.84      0.80      0.77       152

              precision    recall  f1-score   support

        -1.0       0.88      0.93      0.90       102
         1.0       0.91      0.84      0.87        80

    accuracy                           0.89       182
   macro avg       0.89      0.88      0.89       182
weighted avg       0.89      0.89      0.89       182

In [109]:
eth_testing_signal_predictions = eth_svm_model.predict(eth_X_test_scaled)
btc_testing_signal_predictions = btc_svm_model.predict(btc_X_test_scaled)

In [110]:
eth_testing_report = classification_report(eth_y_test, eth_testing_signal_predictions)
print(eth_testing_report)

btc_testing_report = classification_report(btc_y_test, btc_testing_signal_predictions)
print(btc_testing_report)

              precision    recall  f1-score   support

        -1.0       0.88      0.80      0.84        85
         1.0       0.85      0.92      0.88       106

    accuracy                           0.86       191
   macro avg       0.87      0.86      0.86       191
weighted avg       0.87      0.86      0.86       191

              precision    recall  f1-score   support

        -1.0       0.69      0.90      0.78        63
         1.0       0.92      0.73      0.82        98

    accuracy                           0.80       161
   macro avg       0.80      0.82      0.80       161
weighted avg       0.83      0.80      0.80       161

In [111]:
btc_X_test

                 SMA5         SMA23
BTC
2021-07-24  31600.268  32875.692609
2021-07-25  32524.408  32909.036087
2021-07-26  34225.178  33104.470435
2021-07-27  35250.694  33212.286522
2021-07-28  36649.716  33450.716087
...               ...           ...
2021-12-27  50222.854  48943.026522
2021-12-28  50387.964  48930.071304
2021-12-29  49764.038  48893.147391
2021-12-30  48937.248  48712.031304
2021-12-31  48415.520  48574.035217

[161 rows x 2 columns]

In [112]:
eth_predictions_df = pd.DataFrame(index=eth_X_test.index)

eth_predictions_df["predicted_signal"] = eth_testing_signal_predictions

eth_predictions_df["actual returns"] = eth_trading_df["actual returns"]

eth_predictions_df["trading_algorithm_returns"] = (
    eth_predictions_df["actual returns"] * eth_predictions_df["predicted_signal"]
)

# Review the DataFrame
eth_predictions_df.head()

            predicted_signal  actual returns  trading_algorithm_returns
ETH
2021-06-24              -1.0        0.035829                  -0.035829
2021-06-25              -1.0       -0.075234                   0.075234
2021-06-26              -1.0       -0.002797                   0.002797
2021-06-27              -1.0        0.049428                  -0.049428
2021-06-28              -1.0        0.055565                  -0.055565

In [113]:
btc_predictions_df = pd.DataFrame(index=btc_X_test.index)

btc_predictions_df["predicted_signal"] = btc_testing_signal_predictions

btc_predictions_df["actual returns"] = btc_trading_df["actual returns"]

btc_predictions_df["trading_algorithm_returns"] = (
    btc_predictions_df["actual returns"] * btc_predictions_df["predicted_signal"]
)

# Review the DataFrame
btc_predictions_df.head()

            predicted_signal  actual returns  trading_algorithm_returns
BTC
2021-07-24              -1.0        0.016486                  -0.016486
2021-07-25              -1.0        0.113696                  -0.113696
2021-07-26              -1.0       -0.027970                   0.027970
2021-07-27              -1.0        0.074178                  -0.074178
2021-07-28              -1.0        0.006514                  -0.006514

In [126]:
import hvplot.pandas
%matplotlib inline

In [133]:
eth_preplot = (1 + eth_predictions_df[["actual returns", "trading_algorithm_returns"]]).cumprod()
eth_preplot.hvplot(title='ETH', width=800, height=300)

:NdOverlay   [Variable]
   :Curve   [ETH]   (value)

In [132]:
(1 + btc_predictions_df[["actual returns", "trading_algorithm_returns"]]).cumprod().hvplot(title='BTC', width=800, height=300)

:NdOverlay   [Variable]
   :Curve   [BTC]   (value)